### ISSUE TITLE
Conf files

### ISSUE THREAD

**Issue by tsujan** [lxqt/qtxdg-tools#1]
To avoid conflict between Qt5 and Q6 versions of `libqtxdg`, we may need to move `lxqt-qtxdg.conf` and `qtxdg.conf` here.

→ https://github.com/lxqt/libqtxdg/pull/278#issuecomment-1086556618

**Comment by yan12125** [comment]
Thanks I forgot here is an issue tracker 😂 

Looks like conf files are used directly by libqtxdg, not qtxdg-mat. Not sure if it's a good idea to move them here.

**Comment by tsujan** [comment]
> Looks like conf files are used directly by libqtxdg, not qtxdg-mat.

`qtxdg-mat` has the command `def-terminal`. Actually, the relation of `qtxdg-mat` to `libqtxdg` is very similar to that of `gio` to `GLib`. So, IMHO, it's OK to give the config files to it.

Anyway, your comment made me find two small problems in `qtxdg-mat`. They aren't related to our discussion. I'll report them after the spitting is complete.

**Comment by tsujan** [comment]
One of the problems I found is this:

As far as I checked, `xdgdefaultapps.cpp` → `XdgDefaultApps::terminal()` can't read `/usr/share/lxqt/(lxqt-)qtxdg.conf` because the file should be directly in the config directory, not inside the `lxqt` sub-directory. Therefore, those two conf files don't seem to have effect. That means a newly created LXQt session doesn't have a default terminal. This isn't a real issue, IMO, because the same thing can be true about the default browser.

However, as I mentioned above, it isn't directly related to the current discussion.

**Comment by yan12125** [comment]
> the relation of `qtxdg-mat` to `libqtxdg` is very similar to that of `gio` to `GLib`

That convinces me :)

> Therefore, those two conf files don't seem to have effect.

Nice catch! I also found that `/usr/share/-qtxdg.conf` (instead of `/usr/share/qtxdg.conf`) is read if `$XDG_CURRENT_DESKTOP` is empty. Not sure what's the cause, though.
```
$ LANG=en_US.UTF-8 XDG_CURRENT_DESKTOP= strace -f qtxdg-mat def-terminal |& grep conf 
access("/usr/bin/qt.conf", F_OK)        = -1 ENOENT (No such file or directory)
access("/home/yen/.config/-qtxdg.conf", F_OK) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/yen/.config/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/yen/.config/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e00) = -1 ENOENT (No such file or directory)
access("/etc/-qtxdg.conf", F_OK)        = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e00) = -1 ENOENT (No such file or directory)
access("/etc/xdg/-qtxdg.conf", F_OK)    = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/xdg/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/etc/xdg/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e00) = -1 ENOENT (No such file or directory)
access("/usr/share/-qtxdg.conf", F_OK)  = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/share/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e70) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/usr/share/-qtxdg.conf", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT, STATX_ALL, 0x7ffd74d33e00) = -1 ENOENT (No such file or directory)
```

**Comment by tsujan** [comment]
Adding support for the default terminal was the most recent change. If we compare it with the default browser, we could say that there's no bug here: the user needs to define his default terminal (if he needs to), as he defines his default browser. But, in that case, we won't need config files.

On the other hand, if we want to define a system-wide default terminal and allow the user to change it, we should change the ~code~ directory of our config files, so that those config files are read. I think it's easy to do so.

**Comment by tsujan** [comment]
I corrected my previous comment: we don't need to change the code. It'll be enough to put those config files in a global config location (e.g., `/etc/xdg/`).

**Comment by tsujan** [comment]
> I also found that /usr/share/-qtxdg.conf (instead of /usr/share/qtxdg.conf) is read if $XDG_CURRENT_DESKTOP is empty.

Yes, you're right. That's like a bug I fixed in `libfm-qt` (https://github.com/lxqt/libfm-qt/pull/766). It can be fixed easily.

EDIT: The fix is here: https://github.com/lxqt/libqtxdg/pull/279

**Comment by luis-pereira** [comment]
I'm aware of this issue. No more time today. Returning to it tomorrow.

**Comment by luis-pereira** [comment]
The conf files are used by `libqtxdg` [here](https://github.com/lxqt/libqtxdg/blob/ae967f4a28b9de86983892004c683fc3d2f8c938/src/qtxdg/xdgdesktopfile.cpp#L532).

That's why I left it in `libqtxdg`. @tsujan is right tough, it will create a conflict. Not exactly sure how to make it coexist in Qt5 and Qt6.

**Comment by tsujan** [comment]
> Not exactly sure how to make it coexist in Qt5 and Qt6.

My suggestion is giving them to `qtxdg-tools` and putting them in an `XDG_CONFIG_DIRS` folder.

**Comment by luis-pereira** [comment]
@tsujan Giving it to `qtxdg-tools` will make `qtxdg-tools` a required dependency for`libqtxdg`.
To address the mentioned issues I updated the [tools-split branch](https://github.com/lxqt/libqtxdg/tree/tools-split).

Off topic: What kind of CMake `find_package()` support does `qtxdg-tools` need ?

**Comment by tsujan** [comment]
> Giving it to qtxdg-tools will make qtxdg-tools a required dependency forlibqtxdg

I think that's very good. With it, we won't need to make `lxqt-session` depend on `qtxdg-tools` directly.

> What kind of CMake find_package() support does qtxdg-tools need ?

Does it need any after the above-mentioned changes?

**Comment by tsujan** [comment]
Oh, sorry, I got confused, thinking only about `lxqt-session` and forgetting everything else!

`qtxdg-tools` needs `libqtxdg`, so it can't be a required dependency for `libqtxdg`; can it?

**Comment by luis-pereira** [comment]
> `qtxdg-tools` needs `libqtxdg`, so it can't be a required dependency for `libqtxdg`; can it?

That will create a circular dependency. So we will have conflicting qt5 and qt6 `qtxdg-tools` installed if we want to have `libqtxdg` qt5 and qt6 installed at the same time.

p.s. I can't find the discussion about `lxqt-session` requiring `qtxdg-mat`. Can you pls explain shortly ?

**Comment by tsujan** [comment]
> So we will have conflicting qt5 and qt6 qtxdg-tools installed if we want to have libqtxdg qt5 and qt6 installed at the same time.

The whole problem with the conf files inside `libqtxdg` is that they make it impossible to install Qt5 and Qt6 (and future) versions of `libqtxdg` beside each other. My idea was that, if we gave them to `qtxdg-tools`, the problem would be solved.

I still don't see why `libqtxdg` should need those conf files *so urgently* (I understand what they do). If a user doesn't work under an LXQt session and doesn't want `qtxdg-tools`, he won't have them. Will that result in a serious problem?

> I can't find the discussion about lxqt-session requiring qtxdg-mat. Can you pls explain shortly ?

https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commit/d2adf5efdc259a63028f8d4f21569c1557b8cfff will be used under LXQt. So, an LXQt session will need `qtxdg-tools`.

BTW, what about that patch? Did you make a merge request at GitLab?

**Comment by luis-pereira** [comment]
> The whole problem with the conf files inside `libqtxdg` is that they make it impossible to install Qt5 and Qt6 (and future) versions of `libqtxdg` beside each other. My idea was that, if we gave them to `qtxdg-tools`, the problem would be solved.

No, it doesn't solve it. It changes the location of the issue.
With the latest tools-split branch it allows to choose whether to install or not the configuration files and to choose it's destination.

> I still don't see why `libqtxdg` should need those conf files _so urgently_ (I understand what they do). If a user doesn't work under an LXQt session and doesn't want `qtxdg-tools`, he won't have them. Will that result in a serious problem?

I don't understand the so urgently  part.
The conf files are already used in `libqtxdg` code.

> https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commit/d2adf5efdc259a63028f8d4f21569c1557b8cfff will be used under LXQt. So, an LXQt session will need `qtxdg-tools`.
> 
> BTW, what about that patch? Did you make a merge request at GitLab?

Merge request is  [here](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48)

**Comment by tsujan** [comment]
> The conf files are already used in libqtxdg code.

Yes, but their absence doesn't create any serious problem: the user doesn't have a default terminal *outside an LXQt session*, (because an LXQt session requires `qtxdg-tools` and so, the conf files).

> Merge request is here

Very good.

**Comment by luis-pereira** [comment]
I forgot to update the `tools-split` branch.

Commit https://github.com/lxqt/libqtxdg/pull/278/commits/2fec4bdd2e0ca182a76f09ea14a956234193094d gives us the power to control the config files.

**Comment by tsujan** [comment]
Let me explain my concern about https://github.com/lxqt/libqtxdg/commit/2fec4bdd2e0ca182a76f09ea14a956234193094d:

Suppose we finish porting LXQt to Qt6 before LXQt 1.2.0. Therefore, LXQt 1.2.0 will have the Qt6 `libqtxdg`, and distro maintainers should include the conf files in it. The user upgrades to LXQt 1.2.0 but he still have several Qt5 apps, which he wants to work as before. So, he needs the Qt5 `libqtxdg` too. But there's no guarantee that distro maintainers recompile it without conf files. Most probably, they'll leave it as it was, i.e., *with* the conf files. Our user can't make a package for himself and can't install the Qt5 `libqtxdg`. The problem remains as it was.

Of course, advanced users could recompile the Qt5 `libqtxdg` without the conf files and install it beside the Qt6 `libqtxdg` but most users couldn't.

On the other hand, with the conf files inside `qtxdg-tools`, the Qt5 `qtxdg-tools` will be upgraded to the Qt6 one, while the Qt5 `libqtxdg` could remain intact. The user will have the choice to remove the latter if he doesn't need it.

**Comment by luis-pereira** [comment]
> Suppose we finish porting LXQt to Qt6 before LXQt 1.2.0. Therefore, LXQt 1.2.0 will have the Qt6 `libqtxdg`, and distro maintainers should include the conf files in it. The user upgrades to LXQt 1.2.0 but he still have several Qt5 apps, which he wants to work as before. So, he needs the Qt5 `libqtxdg` too. But there's no guarantee that distro maintainers recompile it without conf files. Most probably, they'll leave it as it was, i.e., _with_ the conf files. Our user can't make a package for himself and can't install the Qt5 `libqtxdg`. The problem remains as it was.

I would say that taking care of that kind of things like that within the "job description" of a maintainer.
A package manager will detect that the config files already exist.
Qt5 and Qt6 can coexist in a system only because the maintainer takes care of it. That's the same thing here.
 
> On the other hand, with the conf files inside `qtxdg-tools`, the Qt5 `qtxdg-tools` will be upgraded to the Qt6 one, while the Qt5 `libqtxdg` could remain intact. The user will have the choice to remove the latter if he doesn't need it.

We don't touch the user `XDG_CONFIG_HOME` file. From a user viewpoint nothing changed.
If the config files are installed to the same path the Qt6 will overwrite the Qt5 one.

If libqtxdg requires qtxdg-tools there will be two `qtxdg-tools`. And if the config files are in qtxdg-tools, then libqtxdg requires qtxdg-tools.

**Comment by tsujan** [comment]
> And if the config files are in qtxdg-tools, then libqtxdg requires qtxdg-tools.

This is what I don't understand. → https://github.com/lxqt/qtxdg-tools/issues/1#issuecomment-1094126097

Anyway, I'm not here to fight for users and distro maintainers ;) In the end, I'll agree with whatever you see fit.

**Comment by luis-pereira** [comment]
We use the config files in `XdgDesktopFile` 

``` 
XdgDesktopFile *terminal = XdgDefaultApps::terminal();
``` 
so if the config files are in `qtxdg-tools`  then `libqtxdg` requires `qtxdg-tools`. Otherwise we end up using `xterm` if installed.

On the other hand, `qtxdg-tools` also requires `libqtxdg`.

p.s. I'm not a packager, and my views on packaging are not that educated.

**Comment by yan12125** [comment]
As an Arch packager, placing conf files in either libqtxdg or qtxdg-tools is fine, and avoiding conflicts with a CMake option is good (better than patching CMake files or removing files manually). Circular dependencies are not good, though. The package manager `pacman` can handle them, but there will be warnings.

As an LXQt dev, I think placing conf files in libqtxdg is slightly better, as qterminal, if installed, will be used by default on LXQt. Anyway, I have no strong opinion on this.

**Comment by yan12125** [comment]
I think this issue is resolved and can be closed?
